name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'  # You can specify the Node version you need

    - name: Install Dependencies
      run: npm install  # This installs your project dependencies

    - name: Run Tests
      run: npm test  # This will run your tests

    - name: Build Project
      run: npm run build  # If you have a build step
