name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Print Node.js version
      run: node --version

    - name: Print npm version
      run: npm --version

    - name: Print working directory
      run: pwd

    - name: List directory contents
      run: ls -alh

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test
